slurm submit update

diff --git a/submit b/submit
--- a/submit
+++ b/submit
@@ -13,13 +13,32 @@
 #SBATCH --mail-user=m_beck52@uni-muenster.de # your mail address
 #SBATCH --nice=100
 
-export GPUS_PER_NODE=4
+echo "<<<< SLURM VARIABLES >>>>>"
+printenv | grep SLURM
+echo "<<<< 'scontrol show jobid -dd' OUTPUT >>>>>"
+scontrol show jobid -dd $SLURM_JOBID
+echo "<<<< GPU INFO >>>>>"
+nvidia-smi -L
+
+if ! command -v module &> /dev/null
+then
+	echo "module not found! using dirty workaround instead"
+
+	echo source /opt/lmod/lmod/init/sh
+	export MODULEPATH=/Applic.HPC/modules/PALMA:/Applic.ZIV/modulefiles/
+	source /opt/lmod/lmod/init/sh
+
+	echo source /etc/profile
+	source /etc/profile
+
+	export HOME=/home/m/m_beck52
+fi
 
 # The first hostname is the master address
 master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
 export MASTER_ADDR=$master_addr
 export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
-export WORLD_SIZE=$((SLURM_JOB_NUM_NODES*GPUS_PER_NODE))
+export WORLD_SIZE=$((SLURM_JOB_NUM_NODES*SLURM_NTASKS_PER_NODE))
 
 # START THE APPLICATION
 module purge
